apiVersion: apps/v1
kind: Deployment
metadata:
  name: podset-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podset-operator
  template:
    metadata:
      labels:
        name: podset-operator
    spec:
      serviceAccountName: podset-operator
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: podset-operator
          # Replace this with the built image name
          image: gandhicloud/podset-operator
          command:
            - podset-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podset-operator"
        - name: app
          image: gandhicloud/podset-operator-main
          command: 
            - /bin/bash
            args:
              - -c
              - |
                echo "Started ......"

                cp /app-files/* /html

                echo 'after copyy .........'
                ls -la /app-files/
                ls -la /html
      
                echo "Completed ......" 
          volumeMounts:
            - name: html
              mountPath: /usr/share/html
          env:
            - name: res_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        # - name: proxycontainer
        #   image: lachlanevenson/k8s-kubectl
        #   command: ["kubectl","proxy","--port=8001"]
        - name: kubectl-apply-deployment-files
          image: lachlanevenson/k8s-kubectl
          volumeMounts:
            - name: html
              mountPath: /html
          command: ["kubectl"]
          args:
            - "apply"
            - "-f"
            - "html"
            - "-R"
            - "--validate=false"