apiVersion: apps/v1
kind: Deployment
metadata:
  name: podset-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podset-operator
  template:
    metadata:
      labels:
        name: podset-operator
    spec:
      serviceAccountName: podset-operator
      containers:
        - name: podset-operator
          # Replace this with the built image name
          image: gandhicloud/podset-operator
          command:
          - podset-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "podset-operator"
        - name: proxycontainer
          image: lachlanevenson/k8s-kubectl
          command: ["kubectl","proxy","--port=8001"]
        - name: app
          image: gandhicloud/g-appdeploy-operator
          env:
            - name: res_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace