apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greetings-operator
  template:
    metadata:
      labels:
        name: greetings-operator
    spec:
      serviceAccountName: greetings-operator
      volumes:
        - name: html
          emptyDir: {}
      containers:
        - name: greetings-operator
          # Replace this with the built image name
          image: gandhicloud/my-greetings-operator
          command:
          - greetings-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "greetings-operator"
        - name: download-kubectl-deployment-files
          image: gandhicloud/greetings-operator-main
          command: ["/bin/bash"]
          args:
            - -c
            - |
              echo "Started ......"

              cp /app-files/* /html

              echo 'after copyy .........'
              ls -la /app-files/
              ls -la /html
    
              echo "Completed ......" 
          volumeMounts:
            - name: html
              mountPath: /usr/share/html
          env:
            - name: res_namespace
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
        - name: apply-kubectl-deployment-files
          image: lachlanevenson/k8s-kubectl
          volumeMounts:
            - name: html
              mountPath: /html
          command: ["kubectl"]
          args:
            - "apply"
            - "-f"
            - "html"
            - "-R"
            - "--validate=false"