apiVersion: apps/v1
kind: Deployment
metadata:
  name: greetings-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: greetings-operator
  template:
    metadata:
      labels:
        name: greetings-operator
    spec:
      serviceAccountName: greetings-operator
      containers:
        - name: greetings-operator
          # Replace this with the built image name
          image: gandhicloud/my-greetings-operator
          command:
          - greetings-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "greetings-operator"
