apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appdeploy.gancloud.com
spec:
  scope: Namespaced
  group: gancloud.com
  version: v1
  names:
    kind: AppDeploy
    singular: appdeploy
    plural: appdeploys
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            image1:
              type: string
              description: "Name of the image 1"
            image2:
                type: string
                description: "Name of the image 2"
            replicaCount:
                type: string
                description: "replicaCount"
            repository:
                type: string
                description: "repository"
            tag:
                type: string
                description: "tag"
            containerPort:
                type: string
                description: "containerPort"
              