apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy-operator
  namespace: g-appdeploy-pro
  labels:
    app: appdeploy-operator
spec:
  selector:
    matchLabels:
      app: appdeploy-operator
  template:
    metadata:
      labels:
        app: appdeploy-operator
    spec:
      containers:
      - name: proxycontainer
        image: lachlanevenson/k8s-kubectl
        command: ["kubectl","proxy","--port=8001"]
      - name: app
        image: gandhicloud/g-appdeploy-operator
        env:
          - name: res_namespace
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        