apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: greetings.app.example.com
spec:
  group: app.example.com
  names:
    kind: Greetings
    listKind: GreetingsList
    plural: greetings
    singular: greetings
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Greetings is the Schema for the greetings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: GreetingsSpec defines the desired state of Greetings
          properties:
            replicas:
              format: int32
              type: integer
          required:
          - replicas
          type: object
        status:
          description: GreetingsStatus defines the observed state of Greetings
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
